# Site settings
title: Alireza Samar blog
email:
description: > # this means to ignore newlines until "baseurl:"
  Musings of a Computer Scientist.
baseurl: ""
url: "http://alirezasmr.github.io"
twitter_username: alirezasmr
github_username:  alirezasmr

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
